# Generated by Django 4.2.5 on 2023-09-24 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tasks', to='api.studentmodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='subjects',
            field=models.ManyToManyField(related_name='task_subjects', to='api.subjectmodel'),
        ),
    ]
